/*
 * tCadastroSocio.java
 *
 * Created on 12 de Novembro de 2008, 23:08
 */
package V2;

import java.util.List;

public class tListarSocio extends javax.swing.JFrame {

    private tMain parent;
    private List<Socio> socios;

    /** Creates new form tCadastroSocio */
    public tListarSocio(tMain parent) {
        this.parent = parent;
        try {
            initComponents();
            this.socios = GerenciadorSocios.listar();
            Object[][] objeto = new Object[this.socios.size()][4];//[socios.size()][4];

            int i = 0;
            for (Socio socio : this.socios) {
                objeto[i][0] = socio.getId();
                objeto[i][1] = socio.getNome();
                objeto[i][2] = socio.getCpf();
                objeto[i][3] = String.format("R$ %.2f", socio.getSaldo());
                i++;
            }
            jTabela.setModel(new javax.swing.table.DefaultTableModel(
                    objeto,
                    new String[]{
                        "Id", "Nome", "CPF", "Saldo"
                    }) {

                Class[] types = new Class[]{
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
        } catch (Exception e) {
            this.dispose();
            this.exibeMensagem(e.getMessage(), false);
        }
    }

    private void exibeMensagem(String texto, boolean ok) {
        if (texto == null && ok) {
            texto = "Operação realizada com sucesso!";
        }
        new tMsg(this, texto, ok).show();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();

        setTitle("Listar Sócios");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados dos Sócios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "CPF", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTabela);
        jTabela.getColumnModel().getColumn(0).setResizable(false);
        jTabela.getColumnModel().getColumn(0).setPreferredWidth(15);
        jTabela.getColumnModel().getColumn(1).setResizable(false);
        jTabela.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTabela.getColumnModel().getColumn(2).setResizable(false);
        jTabela.getColumnModel().getColumn(3).setResizable(false);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    this.dispose();
}//GEN-LAST:event_formWindowClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    // End of variables declaration//GEN-END:variables
}
